#!/usr/bin/python3

import sqlite3,sys

if len(sys.argv) < 2 :
	print('Usage:',sys.argv[0],'SUBSTRING-1 SUBSTRING-2 SUBSTRING-3 ...')
	sys.exit(1)

s_list = ['"%' + sys.argv[i].lower() + '%"' for i in range(1, len(sys.argv))]
s_list = [f'''(
	lower(title) LIKE {i} 
	OR lower(actor_name) LIKE {i}
	OR lower(director_name) LIKE {i}
)''' for i in s_list]

con = sqlite3.connect('a2.db')
cur = con.cursor()

query = '''
SELECT title, year, content_rating, imdb_score 
FROM (
	SELECT m.title, m.year, m.content_rating, r.imdb_score, group_concat(ac.name) as actor_name, group_concat(d.name) as director_name
	FROM movie m
		LEFT JOIN rating r on m.id=r.movie_id
		LEFT JOIN acting a on a.movie_id=m.id
		LEFT JOIN actor ac on ac.id=a.actor_id
		LEFT JOIN director d on m.director_id=d.id
	GROUP BY m.title, m.year, m.content_rating, r.imdb_score)
WHERE
'''

for i, _ in enumerate(s_list):
	query += s_list[i]
	if i == (len(s_list) - 1):
		query += '''
		GROUP BY title, year, content_rating, imdb_score
			ORDER BY year DESC, imdb_score DESC, title ASC;
		'''
		break
	query += 'AND'

cur.execute(query)
t = cur.fetchall()

for i in range(len(t)):
	title, year, rating, imdb = t[i]
	imdb = round(float(imdb),1)
	l = [i for i in (year, rating, imdb) if not i == None]

	cur.execute('''
		SELECT g.genre 
		FROM genre g
			INNER JOIN movie m ON g.movie_id=m.id
		WHERE m.title=?
	''', (title,))
	genre= cur.fetchall()
	genre = [i[0] for i in genre]
	print(f'{i+1}. {title} ({", ".join(map(str,l))}) [{",".join(map(str,genre))}]')

con.close()
